apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: guestbook
  namespace: guestbook
spec:
  promotionPolicies:
    - autoPromotionEnabled: true
      stage: test
    - autoPromotionEnabled: true
      stage: uat
    - autoPromotionEnabled: true
      stage: prod-uswest