apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: standard-process
  namespace: guestbook
spec:
  vars:
  - name: stage
  steps:
  # - uses: git-clone
  #   config:
  #     repoURL: https://github.com/emilyxinyi/kargo.git
  #     checkout:
  #     - path: ./configs
  - uses: git-clone
    config:
      repoURL: https://github.com/emilyxinyi/kargo.git
      checkout:
      - branch: main
        path: ./src
      - branch: stage/${{ vars.stage }}
        create: true
        path: ./out
  - uses: git-clear
    config:
      path: ./out
  - uses: kustomize-set-image
    as: update-image
    config:
      path: ./src/guestbook/base
      images:
      - image: ghcr.io/emilyxinyi/guestbook
  - uses: kustomize-build
    config:
      path: ./src/guestbook/stages/${{ vars.stage }}
      outPath: ./out/manifests.yaml
  # - uses: git-commit
  #   config:
  #     path: ./configs
  - uses: git-commit
    as: commit
    config:
      path: ./out
      messageFromSteps:
      - update-image
  # - uses: git-push
  #   config:
  #     path: ./configs
  - uses: git-push
    config:
      path: ./out
      targetBranch: stage/${{ vars.stage }}
  # - uses: argocd-update
  #   config:
  #     apps:
  #     - name: ${{ vars.app }}-${{ ctx.stage }}
  - uses: argocd-update
    config:
      apps:
      - name: guestbook-${{ vars.stage }}
        sources:
        - repoURL: https://github.com/emilyxinyi/kargo.git