apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: app
        value: guestbook
      steps:
      - task: 
          name: standard-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - test
      requiredSoakTime: 2m0s
  promotionTemplate:
    spec:
      vars:
      - name: app
        value: guestbook
      steps:
      - task: 
          name: standard-process
      - uses: http
      as: cat-facts
      config:
        method: GET
        url: https://www.catfacts.net/api/
        outputs:
        - name: status
          fromExpression: response.status
        - name: fact1
          fromExpression: response.body.facts[0]
        - name: fact2
          fromExpression: response.body.facts[1]
  verification:
    analysisTemplates:
    - name: guestbook-verification-3
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-useast
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      # vars:
      # - name: gitRepo
      #   value: https://github.com/emilyxinyi/kargo.git
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/emilyxinyi/kargo.git
          checkout:
          - branch: main
            path: ./src
          # - commit: ${{ commitFrom(vars.gitRepo) }}
          #   path: ./src
          - branch: stage/prod-useast
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/guestbook/base
          images:
          - image: ghcr.io/emilyxinyi/guestbook
      - uses: kustomize-build
        config:
          path: ./src/guestbook/stages/prod-useast
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        as: push
        config:
          path: ./out
          generateTargetBranch: true
          # targetBranch: stage/prod-useast
      - uses: git-open-pr
        as: open-pr
        config:
          repoURL: https://github.com/emilyxinyi/kargo.git
          createTargetBranch: true
          sourceBranch: ${{ outputs.push.branch }}
          # targetBranch: stage/${{ ctx.stage }}
          targetBranch: stage/prod-useast
      - uses: git-wait-for-pr
        as: wait-for-pr
        config:
          repoURL: https://github.com/emilyxinyi/kargo.git
          prNumber: ${{ outputs['open-pr'].prNumber }}
      - uses: argocd-update
        config:
          apps:
          - name: guestbook-prod-useast
            sources:
            - repoURL: https://github.com/emilyxinyi/kargo.git
              desiredRevision: ${{ outputs.wait-for-pr.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-uswest
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      vars:
      - name: app
        value: guestbook
      steps:
      - task: 
          name: standard-process