apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat
      - stage: prod-useast
      - stage: prod-uswest
  template:
    metadata:
      name: guestbook-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: guestbook:{{stage}}
    spec:
      project: default
      source:
        repoURL: ${GITOPS_REPO_URL}
        targetRevision: guestbook/stage/{{stage}}
        path: guestbook/stages/{{stage}}
      destination:
        server: https://kubernetes.default.svc
        namespace: guestbook-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true