apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-guestbook
spec:
  project: kargo-demo
  source:
    repoURL: https://github.com/EmilyXinyi/kargo.git
    path: kargo
  destination:
    server: https://cc19n7e2dnosprep-cplane.kargosvcs.akuity.cloud
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
